---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        # There is a bug in py 2.7.5 tarfile module as described here
        # https://github.com/saltstack/salt/issues/41385#issuecomment-303768986
        # And since this test means to test the formula againest the system in general,
        # So it's fixed manualy here.
        - "sed -i 's/nts(s) or/nts(s).strip() or/' /usr/lib64/python2.7/tarfile.py"
      run_command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init

provisioner:
  name: salt_solo
  log_level: quiet
  require_chef: false
  formula: flume
  state_top:
    base:
      '*':
        - flume

suites:
  - name: default
    provisioner:
      pillars-from-files:
        flume.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - flume
