---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
    driver_config:
      run_command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init

provisioner:
  name: salt_solo
  log_level: quiet
  require_chef: false
  formula: flume
  state_top:
    base:
      '*':
        - flume

suites:
  - name: default
    provisioner:
      pillars-from-files:
        flume.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - flume
