sudo: required
language: python
cache: bundler
services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-centos-7
    - INSTANCE: default-ubuntu-1604

script:
    - bundle exec kitchen verify ${INSTANCE}
